### ISSUE TITLE
Not sure where CA2 is downloading the applications into

### ISSUE THREAD

**Issue by memoriesdota** [ca2/app#9]
All of the downloads don't show up into a folder, I assume it's because ca store is only downloadable as an executable. I think it's better that all the downloads show up into a downloadable folder rather than executable. Or that the downloads are hidden somewhere, not sure. Searching in app/dataroaming does not indicate a folder where the downloads go.

**Comment by camilosasuketbs** [comment]
Applications are installed in folders under %APPDATA%.
Like the app called internally "app/app", is installed at %APPDATA%/app/app
